### ISSUE TITLE
Send point to back on click

### ISSUE THREAD

**Issue by emmorris** [RhoInc/safety-outlier-explorer#105]
Request from Jack.  Sometimes in the Outlier Explorer plots there are subjects who overlap with values at a given timepoint, and you cannot see the individual subject data until you click on a line.

Example: Cohort 2, Measure = QS – Severity of Alopecia Tool – Total Score, Site = 06.

Upon first glance it looks like 3 subjects, but there are 4, and there are 3 subjects with values hovering around 100 for the first few weeks.  Is there a way to tease out the data that occupy the same space? For example, some sort of horizontal offset? 

The group discussed and agreed that an automatic offset should be an easy fix for this.

**Comment by jwildfire** [comment]
@pburnsdata @samussiah @emmorris I remember discussing the technical implementation here in our meeting with Jack, but don't remember the final solution. I think we decided that jittering wasn't a great idea, and that we would make it so that clicking a line we would send it to the back of the canvas, which would then allow Jack to click through overlapping points to get information about each one in turn. Does that sound right?

**Comment by emmorris** [comment]
@jwildfire , I don't think we picked a solution during the meeting.  Jack was okay with whichever option ended up being easiest.  Options were jittering the points (maybe having a toggle to turn that on or off) or clicking a point/line to send it to the back of the canvas so you can rotate through them.  I think your solution should work well.

**Comment by jwildfire** [comment]
## Test Notes

Confirm that points are sent to the back of the canvas when clicked. To test, find a view where there are overlapping points, click multiple times and confirm that details for different participants are shown.

**Comment by dschwentker** [comment]
Tested and passed.
