### ISSUE TITLE
Unfiltered graph shows overlapping values

### ISSUE THREAD

**Issue by rchronowic** [RhoInc/safety-outlier-explorer#132]
Jack mentioned when hovering in the unfiltered graph, only one subject number is shown.
 
This issue is similar to the one below. 
https://github.com/RhoInc/safety-outlier-explorer/issues/105

# Test notes
* Click a point that overlaps with another point.
  * All marks (points, lines) associated with that participant should highlight.
  * A note should appear beneath the chart detailing which participants have results overlapping with the click mark.
  * Hovering over any ID in the note should highlight that participant in the chart above.
  * Clicking any ID in the note should highlight that participant in the chart above and display that participant's measures below.
* With an overlapping point highlighted, changing any control should remove the note but maintain the highlighting of the selected participant.

**Comment by emmorris** [comment]
A little more information from Jack's initial request:  If you look, for example, at Outlier Explorer for basophils, you see it says 12 of 15 participants but it appears that there are only a couple of subjects.  If I flip through each site I can see that the problem is that the subjects appear to have overlapping values, but if you hover over any of the data-points on the unfiltered graph it only shows one subject number.  This is an easy work-around (by filtering), but is there a provision for alerting the user that what appears to be a single data-point is actually more than one overlapping subject (and not just showing as if it were a single subject)?

**Comment by jwildfire** [comment]
Now clicking a point will list overlapping participants as shown below: 

![image](https://user-images.githubusercontent.com/3680095/62997871-74d62b80-be1e-11e9-83d9-4bacc30f47ad.png)

**Comment by jwildfire** [comment]
@samussiah - unless you're opposed, I'm going to get rid of the radius changes that were happening on highlight and on select since they complicate the overlap calculations

**Comment by jwildfire** [comment]
Also getting rid of the `reorderMarks()` functionality, since it's not really needed with the new functionality.
